### ISSUE TITLE
Products, emails, orders didn`t started!

### ISSUE THREAD

**Issue by mpa74** [cyantarek/django-microservices#1]
Images services_products_web, services_email_web, services_orders_web didn`t work properly.

**LOG for services_products_web:**
No module named 'rest_framework_swagger'

**LOG for services_email_web:**
Apply all migrations: api
Running migrations:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 806, in parse
    return handler(self, statement)
  File "/usr/local/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 848, in _create
    self.db.create_collection(table)
  File "/usr/local/lib/python3.6/site-packages/pymongo/database.py", line 365, in create_collection
    raise CollectionInvalid("collection %s already exists" % name)
pymongo.errors.CollectionInvalid: collection api_email already exists

**LOG for services_orders_web:**
 Apply all migrations: api
Running migrations:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 806, in parse
    return handler(self, statement)
  File "/usr/local/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 848, in _create
    self.db.create_collection(table)
  File "/usr/local/lib/python3.6/site-packages/pymongo/database.py", line 365, in create_collection
    raise CollectionInvalid("collection %s already exists" % name)
pymongo.errors.CollectionInvalid: collection api_order already exists

**OS: Tested in Windows 10 and Ubuntu 16**

**Comment by ml-kessoum** [comment]
Hey,
Did you install requirements?
